fname = input("type your fname:")
lname = input("type your lname:")
print("fname:" + fname)
print(type(fname))
print("lname:" + lname)
print(type(fname))

x=int(input("ป้อนตัวเลขตัวที่ 1 : ")) 
y=int(input("ป้อนตัวเลขตัวที่ 2 : "))
print(x+y)